---
galaxy_info:
  author: Shane McDonald
  description: Deploy Ansible Automation Platform on OpenShift
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all

dependencies: []
